### ISSUE TITLE
Mesclar as branchs sem nenhum conflito

### ISSUE THREAD

**Issue by SantosVicente** [SchoolCad/JavaCrud#5]

**Comment by MatheusCamargoGinebro** [comment]
Pra fazer isso precisaremos fazer modificações nas três funções... dentre elas eu identifiquei essas aqui: 👍🏻 
- É legal transformar a parte do edit numa função também, assim como o create e o delete, e tbm pq ela se repete 3 vezes (em professor, sala e aluno;

-Pelo o que eu entendi, a função delete tá separando cada linha com ":" pq estava bugando separar com "|"? se for isso, isso só aconteceu pois quando o @vct-h-dias estava fazendo a função de delete, a parte que separava as linhas com "|" ainda n estava pronta, portanto não havia como separar...
     -> Porém agora da pra separar com "|" tranquilo... a gente faz a modificação de boa.
     
- acho q quando for juntar tudo, tem q cuidar pra n trazer os bugs junto... Exemplo: na versão do código do @SantosVicente  (Main), na parte de salvar o professor no arquivo, estava salvando como "professor:{ID}", mas devia salvar como "professor: {ID}" (o que está acontecendo na minha versão (não vi na do Victor ainda)).

--> Eu só identifiquei esses 3 pontos... mas se vcs souberem de mais algum coloquem aqui até a hora q a gente for juntar tudo.
